# .github/workflows/deploy.yml
name: Build & Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read           # for checkout
  pages: write             # for deploy-pages
  id-token: write          # required by deploy-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Build static site
        run: npm run build
        # your `build` script already does `next build && next export -o docs`

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs    # ← point at the folder with your exported HTML

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
