name: Build & Deploy Phoenix Dashboard

on:
  push:
    branches:
      - main

permissions:
  pages: write           # for deploy-pages
  id-token: write        # for deploy-pages (OIDC)
  contents: read         # for checkout

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://<your-username>.github.io/phoenix-dashboard/

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build static export
        run: npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out/phoenix-dashboard

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
